available_text_models: ["gpt-4.1-2025-04-14"]

info:
  gpt-4.1-2025-04-14:
    type: chat_completion
    name: GPT-4.1 Mini
    description: GPT-4.1 Mini is a <b>fast</b>, <b>cheap</b>, and fairly <b>smart</b> model. Ideal for everyday tasks where efficiency and affordability are important.

    price_per_1000_input_tokens: 0.00015
    price_per_1000_output_tokens: 0.0006

    scores:
      Smart: 4
      Fast: 5
      Cheap: 5

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006